### ISSUE TITLE
CORS Headers

### ISSUE THREAD

**Issue by EricSoroos** [global-electrification-platform/data-service#77]
Should we send CORS headers from the API server to fix the front-end issue: https://github.com/global-electrification-platform/explorer/issues/212?

From my understanding, there aren't any credential issues, so it should be safe to have a fully open CORS setup on the api.

**Comment by vgeorge** [comment]
CORS was already implemented, this was a HTTPS issue. See https://github.com/global-electrification-platform/explorer/issues/212.
