### ISSUE TITLE
Configure deploy to Beanstalk

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/data-service#78]
@EricSoroos, I'm opening this to keep a log of how we will implement the CI. The current CircleCI file is outdated, I was deploying manually using `aws eb deploy`. 

Please let me know needs to be changed to deploy to the new infra-structure.

**Comment by EricSoroos** [comment]
Ultimately it will be a webhook in the repo to CodePipeline.  CodePipeline is configured to take a branch and deploy it to EB. It's a couple clicks on the AWS side.

**Comment by vgeorge** [comment]
Closing this as there will be no deploy to EB on the new staging setup.
