### ISSUE TITLE
Ingest Zambia (zm-1)

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/data-service#79]
@EricSoroos we need to ingest one final country, Zambia. We have a ingest machine at AWS loaded with input data and ready to ingest. Which information do you need to allow it to connect to the new RDS instance?

**Comment by EricSoroos** [comment]
I'll need the IP address of the ingest machine and your public key.

**Comment by vgeorge** [comment]
@EricSoroos sent via e-mail! thanks.

**Comment by vgeorge** [comment]
The ingest process was started now.

**Comment by vgeorge** [comment]
Credentials to the new RDS sent via e-mail weren't working working for me, so Zambia was ingested at our instance. We will need to sent you another snapshot containing Zambia and model config changes that we had to do for the launch.
